### ISSUE TITLE
The same day of the week as the start of each month

### ISSUE THREAD

**Issue by dimitrije-salic-nimbus-tech** [Mina-Massoud/next-ui-full-calendar#2]
Hello, thanks for working hard on this library, very well done!

I noticed some issues while trying to test it:
- In month view, first day of each month is always Saturday

![Screenshot 2024-10-21 at 10 41 29](https://github.com/user-attachments/assets/e2bdfd55-e0d8-4fb8-9a28-068dad1f396e)

**Comment by Mina-Massoud** [comment]
Thank you again for your time in testing. I noticed the issue, and it should be fixed now in the latest version of npm (1.0.0).

Thank you.
