### ISSUE TITLE
Icons sizes and style

### ISSUE THREAD

**Issue by dimitrije-salic-nimbus-tech** [Mina-Massoud/next-ui-full-calendar#3]
Can you please align style and sizes of the icons? Day icon and add event icon is bigger and thicker then week and month icon

![Screenshot 2024-10-21 at 10 37 57](https://github.com/user-attachments/assets/96083e34-58a5-4812-9eae-cb9fa37c7c3a)

**Comment by Mina-Massoud** [comment]
Thank you for the feedback. Please check it now—it should be aligned with the same icons in terms of size and positioning. 

You can also provide your custom tabs components like this example:  
![image](https://github.com/user-attachments/assets/ba3cabdd-4c17-416b-94ce-f271ec1ba4f4)
