### ISSUE TITLE
Align daily view and fix paddings

### ISSUE THREAD

**Issue by dimitrije-salic-nimbus-tech** [Mina-Massoud/next-ui-full-calendar#4]
Can you please align daily view with week and month? Padding needs to be removed as it doesn't exist in other views

<img width="430" alt="image" src="https://github.com/user-attachments/assets/0bcf9a4d-6891-43d5-8aaf-72ad67b8785d">

Also, can you remove p-3 from the <div className="flex w-full flex-col p-3"> from SchedulerViewFilteration so you allow client to decide what would be the padding of the wrapper

<img width="553" alt="image" src="https://github.com/user-attachments/assets/029d6ebc-0df0-4e0b-ba41-6603147ce264">

**Comment by Mina-Massoud** [comment]
I've removed the extra padding! Thank you for pointing out the issue!  
Note: You can use the following to remove any extra padding if needed:  
```jsx
classNames={{ tabs: { panel: 'p-0' } }}
```

Here's an example of how it should look:  
![Example Image](https://github.com/user-attachments/assets/f49c600f-30d4-4a2c-bc46-ac32a0fb6130)"
