### ISSUE TITLE
Days in months

### ISSUE THREAD

**Issue by dimitrije-salic-nimbus-tech** [Mina-Massoud/next-ui-full-calendar#5]
The days of the week should not change, but Monday should always be **the first** day in the calendar on every page

![Screenshot 2024-10-24 at 19 58 03](https://github.com/user-attachments/assets/0d5278c1-6f66-4173-80e5-93c1a807dc7a)
![Screenshot 2024-10-24 at 19 58 06](https://github.com/user-attachments/assets/a1500f1a-a5f9-4342-83e2-78d93614bd2b)

**Comment by Mina-Massoud** [comment]
Thank you for this great feedback!

By setting weekStartsOn to Monday, you will see that the month view now starts with Monday."

![image](https://github.com/user-attachments/assets/4fe1b74e-126a-4d08-bae1-8191e139df42)
![image](https://github.com/user-attachments/assets/3af0495a-18f5-4da5-b769-5998a635abc9)
